### ISSUE TITLE
Error generating docs

### ISSUE THREAD

**Issue by ahmad88me** [dgarijo/Widoco#265]
The ontology can be found [here](https://github.com/ahmad88me/CompanyOntologyStudy/tree/master/CoreBusiness)

The command is: `java -jar  -Dfile.encoding=utf-8 widoco.jar  -rewriteAll  -ontFile 'CoreBusiness/business-v1.00.rdf' -outFolder 'CoreBusiness/business-v1.00.rdf/documentation' -getOntologyMetadata  -saveConfig OnToology/CoreBusiness/business-v1.00.rdf/documentation/business-v1.00.rdf.widoco.conf -htaccess`

The error:
```
Annotation(<http://creativecommons.org/ns#attributionName> "European Commission"@en)
Annotation(<http://creativecommons.org/ns#attributionURL> <http://ec.europa.eu/>)
Annotation(<http://purl.org/dc/terms/abstract> "The Business Core Vocabulary provides a minimum set of classes and properties for
    describing a registered legal entity (business). Its limited scope does not include sole traders, or
    relationships between registered legal entities. This vocabulary is closely integrated with the
    Location and Person Core Vocabularies."@en)
Annotation(<http://purl.org/dc/terms/conformsTo> <https://joinup.ec.europa.eu/elibrary/document/isa-deliverable-process-and-methodology-developing-core-vocabularies>)
Annotation(<http://purl.org/dc/terms/creator> _:genid6)
Exception in thread "main" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at widoco.WidocoUtils.getValueAsLiteralOrURI(WidocoUtils.java:287)
	at widoco.Configuration.completeMetadata(Configuration.java:498)
	at widoco.Configuration.lambda$loadPropertiesFromOntology$1(Configuration.java:392)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at widoco.Configuration.loadPropertiesFromOntology(Configuration.java:392)
	at widoco.gui.GuiController.<init>(GuiController.java:188)
	at widoco.gui.GuiController.main(GuiController.java:409)
```

**Comment by dgarijo** [comment]
Ohh it looks like they used blank nodes in annotation properties and that causes the tool to fail. 
Bad thing is that I won't probably be able to deal with this issue in the next 3 weeks. Please remind me afterwards if I don't fix this issue.
