### ISSUE TITLE
GuiController error

### ISSUE THREAD

**Issue by ahmad88me** [dgarijo/Widoco#281]
Command: `java -jar  -Dfile.encoding=utf-8 /home/vagrant/widoco/widoco.jar  -rewriteAll  -ontFile 'alo.owl' -outFolder 'OnToology/alo.owl/documentation' -getOntologyMetadata  -saveConfig OnToology/alo.owl/documentation/alo.owl.widoco.conf -htaccess`
Ontology: https://github.com/ahmad88me/demo

Error:
```CRITICAL: Exception in thread "main" java.lang.UnsupportedClassVersionError: widoco/gui/GuiController : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by dgarijo** [comment]
I cannot reproduce this issue. I ran:

`java -jar widoco-1.4.2-jar-with-dependencies.jar -rewriteAll -ontFile testOntos/alo.owl -getOntologyMetadata -saveConfig config  -htaccess -outFolder "myDocumentation"`

The documentation was generated successfully. Looks like a java error. Please try again to see if happens to you with other ontologies or only this one. And please make sure that you have the correct jar

**Comment by ahmad88me** [comment]
@dgarijo it works with 1.3.1 but the latest two releases of Widoco does not work. I have a vagrant file with a bootstrap shell if you want to re-generate the error. 
Cheers,

**Comment by dgarijo** [comment]
Maybe it's due to the java version you have installed?
Mine is java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)

**Comment by dgarijo** [comment]
Yes, this seems to be the issue. See: https://stackoverflow.com/questions/18946744/error-in-java-lang-classloader-loadclassunknown-source. You are running an older java version. I think I uploaded the version to introduce some updates.
