### ISSUE TITLE
Remove X dependency

### ISSUE THREAD

**Issue by jgeluk** [dgarijo/Widoco#305]
Can't launch the jar without any parameters:

```
java -jar /usr/share/java/widoco/widoco-launcher.jar 
Error while extracting the reosurces: tmp1536507828469/ajax-loader.gif (No such file or directory)
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:188)
	at widoco.gui.GuiStep1.<init>(GuiStep1.java:48)
	at widoco.gui.GuiController.<init>(GuiController.java:56)
	at widoco.gui.GuiController.main(GuiController.java:442)
```

Ideally when launched without parameters one would expect to see the version number and the help.

**Comment by dgarijo** [comment]
When launched without parameters, a GUI comes up. That is why the display variable error appears. I will try to show up a message with the version too.
