### ISSUE TITLE
Error generating the documentation

### ISSUE THREAD

**Issue by ahmad88me** [dgarijo/Widoco#447]
**Describe the bug**

Error in generating the documentation

**To Reproduce**

1. ```java -jar  -Dfile.encoding=utf-8 widoco/widoco.jar  -rewriteAll  -ontFile 'ontology/deudaPublicaFinanciera.owl' -outFolder 'ontology/deudaPublicaFinanciera.owl/documentation' -confFile ontology/deudaPublicaFinanciera.owl/documentation/deudaPublicaFinanciera.owl.widoco.conf -crossRef -htaccess -lang en```
2. Ontology: https://raw.githubusercontent.com/ahmad88me/vocab-economia-deuda-financiera/master/ontology/deudaPublicaFinanciera.owl

**Expected behavior**
To generate the documentation

**Screenshots**
```
[main] INFO widoco.gui.GuiController - 

--WIzard for DOCumenting Ontologies (WIDOCO).
 https://w3id.org/widoco/

[main] ERROR widoco.WidocoUtils - Error while extracting the reosurces: tmp1613402485430/ajax-loader.gif (No such file or directory)
[main] WARN widoco.Configuration - Error while reading configuration properties from [/home/ahmad/widoco/config/config.properties]: widoco/config/config.properties (No such file or directory)
[main] WARN widoco.Configuration - Error while loading the default property file: /home/ahmad/widoco/config/config.properties (No such file or directory)
[main] INFO widoco.gui.GuiController - Processed configuration, loading ontology now. isFromFile=true
[main] INFO widoco.WidocoUtils - Load ontology ontology/deudaPublicaFinanciera.owl
[main] INFO widoco.CatalogIRIMapper - Creating JenaCatalogIRIMapper
[main] WARN org.semanticweb.owlapi.util.SAXParsers - http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl, error message: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
[main] WARN org.semanticweb.owlapi.util.SAXParsers - entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl, error message: Property 'entityExpansionLimit' is not recognized.
[main] INFO widoco.gui.GuiController - Generating documentation for ontology/deudaPublicaFinanciera.owl in lang en
[main] INFO widoco.CreateResources - Generate documentation in ontology/deudaPublicaFinanciera.owl/documentation
[main] INFO widoco.CreateResources - - ontology IRI: http://vocab.ciudadesabiertas.es/def/economia/deuda-publica-financiera
Error 
  I/O error reported by XML parser processing tmp1613402485430/extraction.xsl:
  tmp1613402485430/extraction.xsl (No such file or directory)
[main] ERROR lode.LODEGeneration - Error while applying LODE. Error while applying the XLS file: Failed to compile stylesheet. 1 error detected.
[main] ERROR widoco.gui.GuiController - Error while generating the documentation: Failed to compile stylesheet. 1 error detected.
javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 1 error detected.
	at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:220)
	at net.sf.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:132)
	at net.sf.saxon.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:87)
	at lode.LODEGeneration.applyXSLTTransformation(LODEGeneration.java:316)
	at lode.LODEGeneration.getLODEhtml(LODEGeneration.java:70)
	at widoco.CreateResources.generateDocumentation(CreateResources.java:72)
	at widoco.gui.GuiController.<init>(GuiController.java:264)
	at widoco.gui.GuiController.main(GuiController.java:490)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 18.04.5 LTS

**Comment by dgarijo** [comment]
After checking with @ahmad88me, it turns out this is not a bug. He had an old version of the JAR file. 

I was not able to reproduce the error, and after @ahmad88me updated the JAR neither was he.
